
- hosts: localhost
  tasks:
    - file:
        path:  roles
        state: absent

    - shell: 
        cmd: 'ansible-galaxy install -r requirements.yml --roles-path roles'
        chdir: '{{ playbook_dir }}'

    - lineinfile:
        dest:   '{{ playbook_dir }}/.gitignore'
        regexp: '^\/roles$'
        line:   '/roles'
        state:  present

- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: netaddr

  role:
    roles:
    - geerlingguy.pip


