
- hosts: localhost

  tasks:
    - file:
        path:  roles
        state: absent

    - shell: ansible-galaxy install -r requirements.yml --roles-path roles
      chdir: {{playbooks_dir}}

    - lineinfile:
        dest:   .gitignore
        regexp: '^\/roles$'
        line:   '/roles'
        state:  present