- hosts: localhost

  tasks:
    - file:
        path:  roles
        state: absent

    - shell: 
        cmd: 'ansible-galaxy install -r requirements.yml --roles-path roles'
        chdir: '{{ playbook_dir }}'

    - lineinfile:
        dest:   '{{ playbook_dir }}/.gitignore'
        regexp: '^\/roles$'
        line:   '/roles'
        state:  present